diffusion:
  type: "all-atom"
  name: "Test_enzyme"
  path: "./outputs/"
  contigs: "10-50/A130-130/10-50/A176-176/10-50/A208-208/10-50"
  pdb: "input_pdbs/7nei_L210T_2pet_15337.pdb"
  iterations: 50
  num_designs: 2
  noise_scale: 1

validation:
  num_seqs: 2
  initial_guess: False
  num_recycles: 1
  use_multimer: False
  rm_aa: ""