FROM nvcr.io/nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04

# Set up environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV DGLBACKEND="pytorch"

# Update and install required packages
RUN apt-get update && apt-get install -y --no-install-recommends     wget ca-certificates git build-essential curl aria2 python3-pip unzip
 
# Install Miniconda
#RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && bash /tmp/miniconda.sh -b -p /opt/conda && rm /tmp/miniconda.sh

RUN cd /tmp && curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

# Add conda to PATH
#ENV PATH=/opt/conda/bin:${PATH}

# Create conda environment and install dependencies
#COPY env/SE3nv.yml /tmp/SE3nv.yml

RUN git clone https://github.com/RosettaCommons/RFdiffusion.git
RUN apt-get -q update \ 
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  git \
  python3.9 \
  python3-pip \
  && python3.9 -m pip install -q -U --no-cache-dir pip \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get autoremove -y \
  && apt-get clean \
  && pip install -q --no-cache-dir \
  dgl==1.0.2+cu116 -f https://data.dgl.ai/wheels/cu116/repo.html \
  torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 \
  e3nn==0.3.3 \
  wandb==0.12.0 \
  pynvml==11.0.0 \
  git+https://github.com/NVIDIA/dllogger#egg=dllogger \
  decorator==5.1.0 \
  hydra-core==1.3.2 \
  pyrsistent==0.19.3 \
  icecream==2.1.3 \
  RFdiffusion/env/SE3Transformer 
  
RUN python3.9 -m pip install --no-cache-dir ./RFdiffusion --no-deps
RUN apt update && apt install git -y

RUN python3.9 -m pip install numpy scipy six wheel -f https://storage.googleapis.com/jax-releases/jax_releases.html


RUN python3.9 -m pip -q install git+https://github.com/sokrypton/ColabDesign.git

RUN python3.9 -m pip install ipykernel
